"""Snake game constants."""

CELL_SIZE = 20
GRID_SIZE = 10
SCREEN_WIDTH = CELL_SIZE * GRID_SIZE
SCREEN_HEIGHT = SCREEN_WIDTH
SCREEN_COLOR = (0, 0, 0)
SNAKE_COLOR = (0, 255, 0)
FOOD_COLOR = (255, 0, 0)
